name: Automatically create PR in Tinderweb on new release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "Dispatch new tag release to TinderWeb"
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: tinder-indumunnangi/TestRepo1
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "tag": "${GITHUB_REF#refs/tags/}"}'
